接收一个python序列转换为array数组

In [1]:
import numpy as np

In [3]:
print(np.version.version)

1.13.1


In [31]:
#来自列表
a = [1,2,3,4,5]
arr = np.array(a)
# arr = np.asarray(a)
print(arr)
print(type(a))
print(type(arr))

[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


In [8]:
#来自元祖
a= (1,2,3,4,5)
# arr = np.array(a)
array = np.asarray(a)
print(arr)
print(type(a))
print(type(arr))

[1 2 3 4 5]
<class 'tuple'>
<class 'numpy.ndarray'>


In [33]:
#来自元祖列表
a = ([1,2,3,4,5],[6,7,8,9,10])
arr = np.array(a)
print(arr)
print(type(a))
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'tuple'>
<class 'numpy.ndarray'>


In [12]:
#创建多维数组
arr = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [10,20,30,40],
        [50,60,70,80],
        [90,100,110,120]
    ]
])
print(arr)

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]]


使用empty,ones,zeros等函数创建数组

In [66]:
arrs = np.empty((3,3),dtype = 'i1')
print(arrs)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
arr = np.ones((3,3))
print(arr)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [65]:
arr = np.zeros((3,3))
print(arr)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


使用其他方式创建数组

In [69]:
arr = np.arange(9)
print(arr)

[1 2 3 4 5 6 7 8]


In [71]:
arr = np.arange(1,9,2)
print(arr)

[1 3 5 7]


In [77]:
arr = np.arange(9,0,-1)
print(arr)

[9 8 7 6 5 4 3 2 1]


In [79]:
#等差数列
arr = np.linspace(0,10,5)
print(arr)

[  0.    2.5   5.    7.5  10. ]


In [80]:
arr = np.linspace(10,20,5,retstep=True)
print(arr)

(array([ 10. ,  12.5,  15. ,  17.5,  20. ]), 2.5)


In [86]:
#等比数列
arr = np.logspace(1,2,5,base = 10)
print(arr)

[  10.           17.7827941    31.6227766    56.23413252  100.        ]


In [84]:
arr = np.logspace(0,10,10,base = 2)
print(arr)

[    2.     4.     8.    16.    32.    64.   128.   256.   512.  1024.]


使用random创建随机数组

In [13]:
#使用随机数创建
arr = np.random.random((3,3))
print(arr)

[[ 0.57881144  0.59327838  0.96211688]
 [ 0.62091924  0.88887448  0.55678564]
 [ 0.1309914   0.19006915  0.49127022]]


In [14]:
arr = np.random.randn(3,3)  #返回一个样本具有标准正态分布
print(arr)

[[ 1.53870348  1.59083422  0.56937182]
 [-0.62385542 -0.08365254  0.78302057]
 [-1.17616326  0.60312881 -0.53224709]]


In [20]:
#返回随机的整数
arr= np.random.randint(1,9,size = (3,3))
print(arr)

[[6 8 4]
 [3 2 6]
 [3 1 3]]


In [22]:
arr= np.random.rand(9)  #返回零到一的随机值
print(arr)

[ 0.60934326  0.22098172  0.37040863  0.53857832  0.23053307  0.7748061
  0.30315933  0.7896444   0.5913902 ]
