ndim 数组轴(维度)的个数，轴的个数被称作秩 

In [2]:
import numpy as np

In [7]:
a = np.random.random((3,3))
print(a)
print(a.ndim)

[[ 0.93325508  0.83922532  0.60555609]
 [ 0.05992577  0.98422395  0.08978786]
 [ 0.47527073  0.62186167  0.41675047]]
2


In [9]:
a = np.arange(9)
print(a)
print(a.ndim)

[0 1 2 3 4 5 6 7 8]
1


shape 数组的形状（维度）, 例如一个2排3列的矩阵，它的shape属性将是(2,3),这个元组的长度显然是秩，即维度或者ndim属性 


In [16]:
a = np.random.random((3,3))
print(a)
print('数组的维度：',a.ndim)
print('数组的形状：',a.shape)


[[ 0.54715618  0.12137212  0.75933174]
 [ 0.25263917  0.86744065  0.4018112 ]
 [ 0.14663017  0.76607588  0.88897577]]
数组的维度： 2
数组的形状： (3, 3)


In [26]:
#shape调整数组的形状
a = np.random.random((2,3))
a.shape = (3,2)
print(a)

[[ 0.62975538  0.92048912]
 [ 0.35810974  0.77695041]
 [ 0.46247008  0.23454661]]


size 数组元素的总个数，等于shape属性中元组元素的乘积。


In [27]:
a = np.random.random((2,3))
print(a)
print('数组的维度：',a.ndim)
print('数组的形状：',a.shape)
print('数组的个数：',a.size)

[[ 0.84931196  0.81045899  0.89538334]
 [ 0.21945656  0.4159351   0.11158765]]
数组的维度： 2
数组的形状： (2, 3)
数组的个数： 6


dtype 一个用来描述数组中元素类型的对象，可以通过创造或指定dtype使用标准Python类型。不过NumPy提供它自己的数据类型。 


In [36]:
# a = np.random.random((2,3))
a = np.random.randint(1,6,size = (2,3))
print(a)
print(a.dtype)

[[1 1 1]
 [4 4 5]]
int32


itemsize返回数组中每个元素的字节单位长度

In [39]:
a = np.random.randint(1,6,size = (2,3))
print(a)
print(a.dtype)
print(a.itemsize)

[[3 3 3]
 [4 1 4]]
int32
4


# Numpy数据类型

In [44]:
a = np.random.randint(1,6,size = (2,3))
print(a)
print(a.dtype)
#通过astype进行类型转换
# a2 = a.astype('f8')
a2 = a.astype(np.float64)
print(a2)
print(a2.dtype)

[[5 2 5]
 [1 3 5]]
int32
[[ 5.  2.  5.]
 [ 1.  3.  5.]]
float64


In [1]:
a = np.array(['Python','java','php','C++'],dtype='<U8')
print(a)
a

NameError: name 'np' is not defined