In [3]:
import numpy as np

# 布尔索引

In [2]:
arr = np.random.random((4,3))
print(arr.shape)
arr

(4, 3)


array([[ 0.13956212,  0.32199118,  0.8481522 ],
       [ 0.53716532,  0.40495091,  0.14117018],
       [ 0.84881948,  0.97534103,  0.41099856],
       [ 0.12178469,  0.52298878,  0.40934973]])

In [3]:
arr2 = arr < 0.5
print(arr2.shape)
arr2

(4, 3)


array([[ True,  True, False],
       [False,  True,  True],
       [False, False,  True],
       [ True, False,  True]], dtype=bool)

In [4]:
arr3 = arr[arr2]  #取出True的元素
arr3

array([ 0.13956212,  0.32199118,  0.40495091,  0.14117018,  0.41099856,
        0.12178469,  0.40934973])

In [5]:
names = np.array(['joe','susan','tom'])
scores = np.array([
    [98,86,88,90],
    [70,86,90,99],
    [82,88,89,86]
])
classic = np.array(['语文','数学','英语','科学'])

In [41]:
names[names=='joe']

array(['joe'],
      dtype='<U5')

In [43]:
name2 = names=='joe'
name2

array([ True, False, False], dtype=bool)

In [6]:
print('joe的成绩是:',scores[names =='joe'].reshape(-1))

joe的成绩是: [98 86 88 90]


In [7]:
print('joe的数学成绩是：',scores[names=='joe',classic=='数学'])
# print('joe的数学成绩是：',scores[names=='joe'].reshape(-1)[classic=='数学'])

joe的数学成绩是： [86]


In [8]:
print('joe和susan的成绩是：')
print(scores[(names=='joe')|(names=='susan')])

joe和susan的成绩是：
[[98 86 88 90]
 [70 86 90 99]]


In [9]:
print('非joe和susan的成绩是：')
print(scores[(names!='joe')&(names!='susan')])

非joe和susan的成绩是：
[[82 88 89 86]]


# 数组转置与轴对换

In [10]:
arr = np.random.randint(1,10,size = (4,5))
print(arr.shape)
arr

(4, 5)


array([[1, 2, 7, 8, 4],
       [8, 9, 6, 4, 9],
       [5, 7, 5, 7, 7],
       [1, 3, 9, 8, 7]])

In [11]:
arr1 = arr.transpose()
print(arr1.shape)
arr1

(5, 4)


array([[1, 8, 5, 1],
       [2, 9, 7, 3],
       [7, 6, 5, 9],
       [8, 4, 7, 8],
       [4, 9, 7, 7]])

In [12]:
arr2 = arr.T
print(arr2.shape)
arr2

(5, 4)


array([[1, 8, 5, 1],
       [2, 9, 7, 3],
       [7, 6, 5, 9],
       [8, 4, 7, 8],
       [4, 9, 7, 7]])

# 常用函数一元一次

In [13]:
arr = np.random.randn(12).reshape(4,3)
arr

array([[-0.03252912, -0.34481256,  1.80681349],
       [ 1.3388692 ,  0.33031531,  0.8276405 ],
       [ 0.81296015,  1.57948341, -0.82288868],
       [-1.17142832, -0.14608915,  0.01120884]])

In [14]:
#abs,fabs绝对值函数
# print(np.abs(arr))
print(np.fabs(arr))

[[ 0.03252912  0.34481256  1.80681349]
 [ 1.3388692   0.33031531  0.8276405 ]
 [ 0.81296015  1.57948341  0.82288868]
 [ 1.17142832  0.14608915  0.01120884]]


In [15]:
#sqrt 计算平方根
arr = np.random.randint(1,10,size=(3,3))
print(np.sqrt(arr))
arr

[[ 1.41421356  2.23606798  3.        ]
 [ 1.73205081  2.44948974  1.73205081]
 [ 1.41421356  1.          2.64575131]]


array([[2, 5, 9],
       [3, 6, 3],
       [2, 1, 7]])

In [16]:
#square计算各个元素的平方
arr = np.random.randint(1,10,size = (3,3))
arr
print(np.square(arr))

[[36  9  1]
 [ 1  9 16]
 [25 16 16]]


In [17]:
# exp()计算各个元素的指数e的x次方
# 自然底数e： e ≈ 2.71828 。。。
num = np.random.randint(1,7,size = (2,3))
print(num)
print(np.exp(num))

[[1 3 2]
 [5 3 4]]
[[   2.71828183   20.08553692    7.3890561 ]
 [ 148.4131591    20.08553692   54.59815003]]


In [18]:
#log()分别计算自然对数、底数为10的log、底数为2的log以及log(1+x)；要求arr中的每个元素必须为正数
num = [
    [9,5,1],
    [3,5,1]
]
print(num)
print(np.log(num))
print(np.log10(num))
print(np.log1p(num))

[[9, 5, 1], [3, 5, 1]]
[[ 2.19722458  1.60943791  0.        ]
 [ 1.09861229  1.60943791  0.        ]]
[[ 0.95424251  0.69897     0.        ]
 [ 0.47712125  0.69897     0.        ]]
[[ 2.30258509  1.79175947  0.69314718]
 [ 1.38629436  1.79175947  0.69314718]]


In [19]:
#sign()计算各个元素的正负号: 1 正数，0：零，-1：负数
num = np.random.randn(1,9).reshape(3,3)
print(num)
print(np.sign(num))

[[-0.54663104 -0.32175795  0.39067704]
 [ 0.82644656 -0.55157679 -0.41458785]
 [ 1.57226836 -0.78192266 -0.71223778]]
[[-1. -1.  1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]]


In [20]:
#ceil向上取整
arr = np.array([-1.7,  1.5,  -0.1,  0.6,  10])
arr = np.ceil(arr)
print(np.ceil(arr))
print(np.sign(arr))

[ -1.   2.  -0.   1.  10.]
[-1.  1.  0.  1.  1.]


In [21]:
#floor向下取整
arr = np.array([-1.7,  1.5,  -0.1,  0.6,  10])
arr = np.floor(arr)
print(np.floor(arr))
print(np.sign(arr))

[ -2.   1.  -1.   0.  10.]
[-1.  1. -1.  0.  1.]


In [22]:
arr = np.array([-1.78,  1.5,  -0.1,  0.6,  10])
print(np.rint(arr))

#  numpy.around(a,decimals)
#  a:输入的数组
#  decimals:要舍入的小数位，默认值位0，负数讲四舍五入到小数点左侧位置
# print(np.around(arr))
# print(np.around(arr,1))
# print(np.around(arr,-1))

[ -2.   2.  -0.   1.  10.]


In [23]:
#modf()将数组中元素的小数位和整数位以两部分独立数组的形式返回
arr = np.random.random(6).reshape(2,3)
print(arr)
print(np.modf(arr))

[[ 0.43469598  0.37817619  0.34673671]
 [ 0.40876217  0.03232201  0.35177667]]
(array([[ 0.43469598,  0.37817619,  0.34673671],
       [ 0.40876217,  0.03232201,  0.35177667]]), array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]]))


In [24]:
#isnan()返回一个表示“那些值是NaN(不是一个数字)”的布尔类型数组
arr = np.random.random(6).reshape(2,3)
print(arr)
print(np.isnan(arr))

[[ 0.5983094   0.04789659  0.77026695]
 [ 0.07016323  0.32383965  0.33600711]]
[[False False False]
 [False False False]]


In [25]:
#分别一个表示”那些元素是有穷的(非inf、非NaN)”或者“那些元素是无穷的”的布尔型数组
num = np.random.random(6).reshape(2,3)
print(num)
print(np.isfinite(num))
print(np.isinf(num))

[[ 0.83941095  0.04836189  0.52712199]
 [ 0.36606486  0.4659995   0.14629659]]
[[ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]]


In [26]:
#三角函数
a = np.array([0,30,45,60,90])
print(np.sin(a*np.pi/180))
print(np.arcsin(np.sin(a*np.pi/180)))
print(np.cos(a*np.pi/180))
print(np.arccos(np.cos(a*np.pi/180)))
print(np.tan(a*np.pi/180))
print(np.arctan(np.tan(a*np.pi/180)))
print(np.degrees(np.arctan(np.tan(a*np.pi/180))))

[ 0.          0.5         0.70710678  0.8660254   1.        ]
[ 0.          0.52359878  0.78539816  1.04719755  1.57079633]
[  1.00000000e+00   8.66025404e-01   7.07106781e-01   5.00000000e-01
   6.12323400e-17]
[ 0.          0.52359878  0.78539816  1.04719755  1.57079633]
[  0.00000000e+00   5.77350269e-01   1.00000000e+00   1.73205081e+00
   1.63312394e+16]
[ 0.          0.52359878  0.78539816  1.04719755  1.57079633]
[  0.  30.  45.  60.  90.]


# 常用二元函数

In [27]:
#mod()元素级的取模
arr1 = np.random.randint(10,15,size = (3,3))
arr2 = np.random.randint(1,5,size = (3,3))
print(arr1)
print(arr2)
print(np.mod(arr1,arr2))

[[10 12 13]
 [11 14 11]
 [13 11 12]]
[[2 4 3]
 [1 3 2]
 [4 2 1]]
[[0 0 1]
 [0 2 1]
 [1 1 0]]


In [28]:
arr1 = np.random.randint(1,5,size = (3,3))
arr2 = np.random.randint(1,5,size = (3,3))
print(arr1)
print(arr2)
print(np.dot(arr1,arr2))

[[1 4 2]
 [4 3 2]
 [3 3 2]]
[[3 1 1]
 [1 1 3]
 [1 1 3]]
[[ 9  7 19]
 [17  9 19]
 [14  8 18]]


In [29]:
# greater() 大于
# less()    小于
# equal()   等于
# 执行元素级别的比较运算，最终返回一个布尔型数组
num1 = np.random.randint(1,7,size = (2,3))
num2 = np.random.randint(1,7,size = (2,3))
print(num1)
print(num2)
print(np.greater(num1,num2))

[[3 6 2]
 [2 5 3]]
[[2 1 1]
 [5 3 3]]
[[ True  True  True]
 [False  True False]]


In [30]:
# logical_and() 
#    logical_or()    
#    logical_xor()   
#    执行元素级别的布尔逻辑运算，相当于中缀运算符&、|、^
num1 = np.random.randint(1,7,size = (2,3))
num2 = np.array([[1,0,0],[1,0,1]])
print(num1)
print(num2)
print(np.logical_and(num1,num2))
print(np.logical_or(num1,num2))
print(np.logical_xor(num1,num2))

[[1 6 4]
 [5 5 4]]
[[1 0 0]
 [1 0 1]]
[[ True False False]
 [ True False  True]]
[[ True  True  True]
 [ True  True  True]]
[[False  True  True]
 [False  True False]]


In [31]:
#power()对数组中的每个元素进行给定次数的指数值，类似于: arr ** 3
nums = np.random.randint(1,7,size = (2,3))
print(nums)
print(np.power(nums,2))

[[4 4 4]
 [6 3 6]]
[[16 16 16]
 [36  9 36]]


# 聚合函数

In [32]:
a = np.array([[5,2,3,4],[7,3,9,1]])
print(a)
print('min:',np.amin(a,0))
print('max:',np.amax(a))
print('min:',np.mean(a,0))
print('min:',a.mean(0))

[[5 2 3 4]
 [7 3 9 1]]
min: [5 2 3 1]
max: 9
min: [ 6.   2.5  6.   2.5]
min: [ 6.   2.5  6.   2.5]


In [33]:
#方差，偏差的平方的平均值
a = np.array([[5,2,3,4],[7,3,9,1]])
print(np.mean((a-a.mean())**2))

6.1875


In [34]:
#标准差 偏差的平方的平均值的平方根
a = np.array([[5,2,3,4],[7,3,9,1]])
print(np.sqrt(np.mean((a-a.mean())**2)))
print(np.std(a))

2.48746859277
2.48746859277


In [4]:
#numpy.where 是三元表达式 x if condition else y 的矢量化版本
a = np.where([[True, False], [True, False]],[[1, 2], [3, 4]],[[9, 8], [7, 6]])
print(a)
print(help(np.where))

[[1 8]
 [3 6]]
Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and i

In [36]:
arr1 = np.random.randint(1,9,size = 6)
arr2 = np.random.randint(1,9,size = 6)
print(arr1)
print(arr2)
condition = arr1 > arr2
arr3 = [xv if c else yv for (c,xv,yv) in zip(condition,arr1,arr2)]
print(arr3)
print(type(arr3))
arr4 = np.where(condition,arr1,arr2)
print(arr4)
print(type(arr4))

[5 4 5 7 7 6]
[8 7 1 6 1 2]
[8, 7, 5, 7, 7, 6]
<class 'list'>
[8 7 5 7 7 6]
<class 'numpy.ndarray'>


In [37]:
#案例：将数组中的所有异常数字替换为0，比如将NaN替换为0
arr = np.array([
    [1,2,np.NaN,4],
    [4,5,6,np.NaN],
    [np.inf,7,8,9],
    [np.inf,np.e,np.pi,4]
])
print(arr)
condition = np.isnan(arr)|np.isinf(arr)
print(np.where(condition,0,arr))

[[ 1.          2.                 nan  4.        ]
 [ 4.          5.          6.                 nan]
 [        inf  7.          8.          9.        ]
 [        inf  2.71828183  3.14159265  4.        ]]
[[ 1.          2.          0.          4.        ]
 [ 4.          5.          6.          0.        ]
 [ 0.          7.          8.          9.        ]
 [ 0.          2.71828183  3.14159265  4.        ]]


In [38]:
#np.uunique函数主要的作用是将数组中的元素进行去重操作（也就是只保存不重复的数据）
arr = np.array(['图书','数码','小吃','数码','男装','小吃','美食','数码','女装'])
print(arr)
arr2 = np.unique(arr)
arr2

['图书' '数码' '小吃' '数码' '男装' '小吃' '美食' '数码' '女装']


array(['图书', '女装', '小吃', '数码', '男装', '美食'],
      dtype='<U2')