# numpy.array
Numpy中定义的最终要的对象是称为ndarray的N维数组类型。它描述相同类型的元素集合。可以使用基于零的索引访问
集合中的项目。
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
上面的构造器接受以下参数：

序号	参数及描述
1.	object 任何暴露数组接口方法的对象都会返回一个数组或任何(嵌套)序列。
2.	dtype 数组的所需数据类型，可选。
3.	copy 可选，默认为true，对象是否被复制。
4.	order C(按行)、F(按列)或A(任意，默认)。
5.	subok 默认情况下，返回的数组被强制为基类数组。 如果为true，则返回子类。
6.	ndimin 指定返回数组的最小维数。


In [1]:
#导入numpy 模块
import numpy as np

In [2]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [3]:
#np.array实例
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
#多维数组
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [7]:
#最小维度
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [10]:
#指定类型
np.array([1, 2, 3], dtype=complex)

array([ 1.+0.j,  2.+0.j,  3.+0.j])

（1）创建一个2*3*4的随机数组
（2）创建一个8*8的“棋盘”（ 用零填充）矩阵。然后将1、3、5、7行的第0、2、4、6列的元素改为1 。
（3）创建一个10*10的数组，并且边框是1，里面是0

In [3]:
arr= np.random.random((2,3,4))
arr

array([[[ 0.99975623,  0.41448056,  0.0758899 ,  0.41667076],
        [ 0.86768624,  0.14380495,  0.93103439,  0.75296399],
        [ 0.59169891,  0.51447085,  0.88983927,  0.87767906]],

       [[ 0.0274444 ,  0.73664641,  0.7086006 ,  0.17426475],
        [ 0.78610044,  0.91257438,  0.59551266,  0.2217407 ],
        [ 0.61314336,  0.09218189,  0.9208482 ,  0.69027658]]])

In [5]:
arr = np.zeros((8,8))
arr
arr[1::2,0::2]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])