In [1]:
import numpy as np

# 创建数组

In [4]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [5]:
# 一维列表创建
np.array([1,2,3])

array([1, 2, 3])

In [7]:
# 用元组创建
np.array((1,2,3))

array([1, 2, 3])

In [8]:
# 二维数组
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.array([
    [
        [1,2,3],
        [2,3,4]
    ],
    [
        [3,4,5],
        [4,5,6]
    ]
])

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]]])

In [12]:
# 通过zeros创建数组 创建一个元素为0的元素
np.zeros((3,3))
# np.zeros((2,3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# ones 生成元素为1的数组
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [20]:
# linspace生成等差数列
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
# logspace生成等比数列
np.logspace(0,2,5) # 10的0次方 到10的2次方
np.logspace(0,2,5, base = 2)

array([1.        , 1.41421356, 2.        , 2.82842712, 4.        ])

In [23]:
# 使用random创建随机数
np.random.random((3,3))

array([[0.64137472, 0.0234958 , 0.25577244],
       [0.35191734, 0.78113988, 0.24459593],
       [0.19750201, 0.46892247, 0.8768387 ]])

In [26]:
np.random.randint(1,10,size=(3,3))

array([[9, 9, 6],
       [5, 5, 6],
       [8, 2, 7]])

In [27]:
np.random.randn(3,3)

array([[ 0.2769483 ,  1.11134388,  0.00863263],
       [-0.59910856,  0.69348869, -0.49600322],
       [ 0.07146511, -0.33880301,  0.99509687]])

In [28]:
np.random.rand(9)

array([0.51510178, 0.9675465 , 0.3280749 , 0.8779577 , 0.2060644 ,
       0.4662378 , 0.49588788, 0.54725231, 0.26561256])