# DataFrame
数据帧(DataFrame)是二维数据结构，即数据以行和列的表格方式排列。

In [17]:
import numpy as np
import pandas as pd

In [18]:
#创建空的dataframe
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [19]:
#通过二维数组创建
data = [['joe','susan','monika'],[70,80,90]]
df1 = pd.DataFrame(data)
df1

#使用ndarray
arr = np.array([
    ['joe',70],    #一个元素代表一列数据。 
    ['suan',80],
    ['monika',90]
])
df2 = pd.DataFrame(arr,columns = ['姓名','语文'])  #设置列索引
print(df2.values)
print(df2.index)
print(df2.columns)
df2

[['joe' '70']
 ['suan' '80']
 ['monika' '90']]
RangeIndex(start=0, stop=3, step=1)
Index(['姓名', '语文'], dtype='object')


姓名  语文
0     joe  70
1    suan  80
2  monika  90

In [20]:
#通过字典的方式创建
dict1 = {
    '语文':[79,80,77,84],  #字典的下标会成为列索引
    '数学':[70,80,88,90],
    '英语':[77,88,99,80],
    '体育':'A'
} 

df3 = pd.DataFrame(dict1,index = ['joe','anne','susan','monika'])#创建的时候设置行索引
#设置行索引
# df3.index = ['joe','anne','susan','monika']
df3

体育  数学  英语  语文
joe     A  70  77  79
anne    A  80  88  80
susan   A  88  99  77
monika  A  90  80  84

In [21]:
#列选择
df3['语文']
df3.loc[:,'数学':'语文']  #选择多列，要先选择行
df3[['数学','语文']]

数学  语文
joe     70  79
anne    80  80
susan   88  77
monika  90  84

In [22]:
#列修改
df3['语文'] = [81,82,83,84]
df3

体育  数学  英语  语文
joe     A  70  77  81
anne    A  80  88  82
susan   A  88  99  83
monika  A  90  80  84

In [23]:
#列增加
df3['历史'] = [87,88,86,85]
df3


体育  数学  英语  语文  历史
joe     A  70  77  81  87
anne    A  80  88  82  88
susan   A  88  99  83  86
monika  A  90  80  84  85

In [32]:
#列删除
# del df3['历史']
df3.pop('历史')
# df3

joe       87
anne      88
susan     86
monika    85
black     90
Name: 历史, dtype: int64

In [33]:
#行选择
# df3.ix['joe']
# df3.ix[0]

# df3.loc['joe']
# df3.iloc[0]

# df3.ix[0:3]
df3.ix['anne':'susan']

体育  数学  英语  语文
anne   A  80  88  82
susan  A  88  99  83

In [34]:
#行增加
df3.loc['black'] = ['B',60,70,80]

df3

体育  数学  英语  语文
joe     A  70  77  81
anne    A  80  88  82
susan   A  88  99  83
monika  A  90  80  84
black   B  60  70  80

In [38]:
#行修改
df3.loc['black'] = ['A',60,70,80]
df3

体育  数学  英语  语文
joe     A  70  77  81
anne    A  80  88  82
susan   A  88  99  83
monika  A  90  80  84
black   A  60  70  80

In [40]:
#行删除
df3 = df3.drop('black')
df3

体育  数学  英语  语文
joe     A  70  77  81
anne    A  80  88  82
susan   A  88  99  83
monika  A  90  80  84

In [37]:
data = np.random.randint(1,9,(8,8))
print(data)
# data[1::2,0::2] = 10
# data

# data[np.ix_([1,3,5,7],[0,2,4,6])] = 10
# data

[[5 8 6 4 6 6 8 6]
 [1 3 6 8 8 1 8 8]
 [7 4 8 3 1 3 4 5]
 [7 5 4 5 3 7 8 2]
 [3 2 1 5 4 2 5 5]
 [1 7 1 5 1 7 1 3]
 [7 8 8 2 3 5 7 2]
 [8 3 2 4 1 1 2 5]]


In [ ]:
data = np.random.randint(1,9,(2,3,3))
data


In [ ]:
data1 = np.unique(data)
data1